---
- name: RedHat - Install required packages
  yum:
    name: "{{ item.key }}{{ '-' + item.version | default('*') }}"
    state: "{{ item.state | default('present') }}"
  with_dict: configdrive_packages
  when: ansible_facts.os_family == 'RedHat'
  tags: ["redhat"]

- name: Debian - Install required packages
  apt: 
    name: "{{ item.key }}{{ '=' + item.version | default('*') }}"
    state: "{{ item.state | default('present') }}"
  with_dict: configdrive_packages
  when: ansible_facts.os_family == 'Debian'
  tags: ["debian"]
